### PR TITLE
added an extensibility point for command deserialization

### PR DESCRIPTION
**Pull request by thefringeninja**

### CODE REVIEW

**Comment by damianh** [comment]
Why is this needed?

**Comment by thefringeninja** [comment]
SimpleJson is not going to handle every scenario. e.g. immutable messages

**Comment by damianh** [comment]
Does this need a reciprocal on the client side?

**Comment by thefringeninja** [comment]
What do you mean reciprocal?

**Comment by damianh** [comment]
Customize the serialization of commands...

**Comment by thefringeninja** [comment]
Yeah... I don't need it right now but I can see a need for that

On Fri, May 15, 2015 at 11:19 AM, Damian Hickey <notifications@github.com>
wrote:

> Customize the serialization of commands...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/damianh/Cedar.CommandHandling/pull/15#issuecomment-102338257>
> .
>



-- 
Sent from my regular computer
http://twitter.com/thefringeninja
http://www.thefringeninja.com/

**Comment by damianh** [comment]
Will leave it until it's needed.

**Pull request merged**
